name: learn-haskell
version: 0.1
maintainer: "Gabriel de la Calzada"

dependencies:
- base >= 4.7 && < 5
- split == 0.2.3.3
- time == 1.8.0.2

library: 
  source-dirs: 
  - Chapter01
  - Chapter02
  - Chapter03
  - Chapter04
  - Chapter05
  - Chapter06
  - Chapter07
  - Chapter08
  - Chapter09
  - Chapter10
  - Chapter11
  - Chapter12
